#!/bin/bash

test -f /etc/ssh/ssh_host_rsa_key || /usr/bin/ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa
test -f /etc/ssh/ssh_host_dsa_key || /usr/bin/ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa
/usr/sbin/sshd -D
